# Generated by Django 4.2.5 on 2023-09-30 21:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("workload", models.PositiveIntegerField()),
                (
                    "professor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="professors_courses",
                        to="users.professor",
                    ),
                ),
                (
                    "students",
                    models.ManyToManyField(
                        related_name="students_courses", to="users.student"
                    ),
                ),
            ],
        ),
    ]
