# Generated by Django 4.2.5 on 2023-10-06 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
        ("courses", "0003_alter_course_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="professor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="professors_courses",
                to="users.professor",
            ),
        ),
    ]
