# Generated by Django 4.2.5 on 2023-10-06 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
        ("courses", "0004_alter_course_professor"),
        ("grades", "0002_alter_grade_course_alter_grade_professor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grade",
            name="course",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="courses_grades",
                to="courses.course",
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="professor",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="professors_grades",
                to="users.professor",
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="student",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="students_grades",
                to="users.student",
            ),
        ),
    ]
